project:
  type: website
  output-dir: docs
  
website:
  title: "jaehee"
  navbar:
    left:
      - href: index.qmdtext: Home
        text: Home
      - href: about.qmdtext: About
        text: About
      - href: post/index.qmd
        text: Blog
format:
  html:
    theme: cosmo
    toc: true



