project:
  type: website
  output-dir: docs
  
website:
  title: "jaehee"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: post/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



